name: "Голос"
slug: "voice"
version: "0.4.0"
description: "Голосовой ассистент на айфоне"
arch:
  - "amd64"
init: false
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: "mdi:microphone-message"
panel_title: "Голос"
ports:
  8091/tcp: 8091
  10700/tcp: 10700
  10701/tcp: 10701
  10702/tcp: 10702
ports_description:
  8091/tcp: "HTTPS для айфона"
  10700/tcp: "Wyoming-спутник: Спальня"
  10701/tcp: "Wyoming-спутник: Гостиная"
  10702/tcp: "Wyoming-спутник: Детская"
options:
  host_ip: "192.168.1.123"
  threshold: 0.45
  margin: 0.08
schema:
  host_ip: "str"
  threshold: "float(0,1)"
  margin: "float(0,1)"
